CREATE TABLE IF NOT EXISTS users
(
    ID          SERIAL NOT NULL,
    UUID        VARCHAR(255) NOT NULL,
    USERNAME    VARCHAR(255) NOT NULL,
    PASSWORD    VARCHAR(255) NOT NULL,
    ACTIVE      BOOLEAN DEFAULT false,
    PRIMARY KEY (id)
);